---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: in this task i want to install webserver on ubuntu
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family== "Debian"  
  - name: i want to start webserver
    service:
      name: "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family== "Debian"