---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: in this task i want to install webserver on ubuntu
    apt:
      name: apache2
      state: present

  - name: i want to satrt webserver 
    service:
      name: apache2
      state: started